name: ✨ Feature Request
description: Suggest a new feature or enhancement for Filemet
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨
        
        Please fill out this form to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: 🏷️ Feature Type
      description: What type of feature is this?
      options:
        - New Framework Template
        - Parser Enhancement
        - UI/UX Improvement
        - Custom Expression Feature
        - Performance Improvement
        - Developer Experience
        - Integration
        - Other
    validations:
      required: true

  - type: input
    id: framework
    attributes:
      label: 🏗️ Framework (if applicable)
      description: If requesting a new framework template, which framework?
      placeholder: "e.g., Vue.js, Angular, Svelte, Django, Ruby on Rails"

  - type: textarea
    id: template-structure
    attributes:
      label: 📁 Proposed Template Structure (if applicable)
      description: If requesting a framework template, provide the desired file structure
      placeholder: |
        Example:
        src/{
          components/{Header.vue,Footer.vue},
          views/{Home.vue,About.vue},
          router/index.js,
          store/index.js
        }
      render: text

  - type: textarea
    id: use-cases
    attributes:
      label: 🎮 Use Cases
      description: Describe specific use cases or scenarios where this feature would be helpful
      placeholder: |
        1. When starting a new project...
        2. When creating component libraries...
        3. When setting up testing frameworks...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: 📊 Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Significantly impacts my productivity
        - Critical - Blocking my current work

  - type: dropdown
    id: complexity
    attributes:
      label: 🧮 Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Small addition or modification
        - Medium - New functionality with moderate changes
        - Complex - Major feature requiring significant development
        - Unknown - Not sure about implementation complexity

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: examples
    attributes:
      label: 📖 Examples
      description: Provide examples of how this feature would work
      placeholder: |
        Example commands, UI mockups, or workflow descriptions

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or references about the feature request
